### List all messages
GET http://localhost:3000/computer

### Create a new message

POST http://localhost:3000/messages
content-type: application/json

{
    "content": "hi there again 1"
}

### Get a particular message
GET http://localhost:3000/messages/115
